/* MTI_DPI */

/*
 * Copyright 2002-2013 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'linux_x86_64'
 */
#ifndef INCLUDED_DPIHEADER
#define INCLUDED_DPIHEADER

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"



#ifndef MTI_INCLUDED_TYPEDEF_mem_packet_t
#define MTI_INCLUDED_TYPEDEF_mem_packet_t

typedef struct {
    char we;
    int addr;
    int size;
}  mem_packet_t;

#endif

DPI_LINK_DECL DPI_DLLESPEC
void
mem_init(
    int port);

DPI_LINK_DECL DPI_DLLESPEC
int
mem_poll(
    mem_packet_t* packet,
    char* buffer);

DPI_LINK_DECL DPI_DLLESPEC
int
mem_push(
    const mem_packet_t* packet,
    const char* buffer);

#endif 
