// reuse-pragma startSub [::RCE::insert_copyright] endSub                 
//----------------------------------------------------------------------  
//                                                                        
//                  (C) COPYRIGHT 2005-2013 SYNOPSYS, INC.                
//                            ALL RIGHTS RESERVED                         
//                                                                        
//  This software and the associated documentation are confidential and   
//  proprietary to Synopsys, Inc.  Your use or disclosure of this         
//  software is subject to the terms and conditions of a written          
//  license agreement between you, or your company, and Synopsys, Inc.    
//                                                                        
//  The entire notice above must be reproduced on all authorized copies.  
//----------------------------------------------------------------------- 
//--                                                                      
// reuse-pragma startSub [format "// Release version :  " [get_attribute [current_design -quiet] -attr {SpiritVersion}]]
// Release version  :                                                     
// Date             :        $Date$                      
// Revision: $Id$                                                      
//--                                                                      
//------------------------------------------------------------------------

// DERIVED PARAMETERS - Auto Generated by ParamsParser.pl

`define BUS_TYPE_AHB
`define INTERNAL_DMAC_YES
`define DW_DMA
`define NO_GENERIC_DMA
`define NO_NON_DW_DMA
`define RAM_DEPTH 128
`define F_COUNT_WIDTH 8
`define FIFO_RAM_INSIDE_CORE
`define CLK_DIV_2
`define NO_AREA_OPTIMIZATION
`define HOLD_REGISTER
`define SD_MODE
`define DMA_BUS_BYTES 32'h4
`define F_DATA_WIDTH_32
`define F_DATA_WIDTH 32
`define F_BYTE_WIDTH 10
`define H_DATA_WIDTH_32
`define M_ADDR_WIDTH_32
