
   `undef USE_FOUNDATION
   `undef MEMCTL_USE_FOUNDATION_IS_ONE
   `undef VER_1_2A_COMPATIABLE_MODE
   `undef H_DATA_WIDTH
   `undef H_ADDR_WIDTH
   `undef PIPE_ADDRESS_DECODER
   `undef ADDR_FIFO_DEPTH
   `undef WRITE_FIFO_DEPTH
   `undef EBI_INTERFACE
   `undef DYNAMIC_RAM_TYPE
   `undef USE_MOBILE_DDR
   `undef MOBILE_DDR_SDRAM
   `undef ENABLE_STATIC
   `undef N_CS
   `undef ENABLE_DATABUS_SHARING
   `undef ENABLE_ADDRBUS_SHARING
   `undef HARD_WIRE_SDRAM_PARAMETERS
   `undef HARD_WIRE_SYNCFLASH_PARAMETERS
   `undef HARD_WIRE_STATIC_PARAMETERS
   `undef HARD_WIRE_CIPSELECT_PARAMETRS
   `undef WRITE_PIPE
   `undef READ_PIPE
   `undef T_REF
   `undef T_INIT
   `undef MAX_S_DATA_WIDTH
   `undef S_DATA_WIDTH
   `undef MAX_S_ADDR_WIDTH
   `undef MAX_S_BANK_ADDR_WIDTH
   `undef HIGHER_ADDR_FOR_BANKS
   `undef HIGHER_ADDR_FOR_SF_BANKS
   `undef NUM_DQS
   `undef EXTENDED_MODE_REG
   `undef SM_WRITE_PIPE
   `undef MAX_SM_DATA_WIDTH
   `undef MAX_SM_ADDR_WIDTH
   `undef T_RPD
   `undef CHIP_SELECT0_MEM
   `undef REG_SELECT0
   `undef CHIP_SELECT0_BASE_ADDRESS
   `undef CHIP_SEL0_REMAP_ENABLE
   `undef CHIP_SEL0_ALIAS_ENABLE
   `undef CHIP_SELECT0_ALIAS_ADDRESS
   `undef CHIP_SELECT0_REMAP_ADDRESS
   `undef CHIP_SELECT1_MEM
   `undef REG_SELECT1
   `undef CHIP_SELECT1_BASE_ADDRESS
   `undef CHIP_SEL1_REMAP_ENABLE
   `undef CHIP_SEL1_ALIAS_ENABLE
   `undef CHIP_SELECT1_ALIAS_ADDRESS
   `undef CHIP_SELECT1_REMAP_ADDRESS
   `undef CHIP_SELECT2_MEM
   `undef REG_SELECT2
   `undef CHIP_SELECT2_BASE_ADDRESS
   `undef CHIP_SELECT3_MEM
   `undef REG_SELECT3
   `undef CHIP_SELECT3_BASE_ADDRESS
   `undef CHIP_SELECT4_MEM
   `undef REG_SELECT4
   `undef CHIP_SELECT4_BASE_ADDRESS
   `undef CHIP_SELECT5_MEM
   `undef REG_SELECT5
   `undef CHIP_SELECT5_BASE_ADDRESS
   `undef CHIP_SELECT6_MEM
   `undef REG_SELECT6
   `undef CHIP_SELECT6_BASE_ADDRESS
   `undef CHIP_SELECT7_MEM
   `undef REG_SELECT7
   `undef CHIP_SELECT7_BASE_ADDRESS
   `undef S_ROW_ADDR_WIDTH
   `undef S_COL_ADDR_WIDTH
   `undef S_BANK_ADDR_WIDTH
   `undef A8_FOR_PRECHARGE
   `undef OPEN_BANKS
   `undef CAS_LATENCY
   `undef T_RAS_MIN
   `undef T_RCD
   `undef T_RP
   `undef T_WR
   `undef T_RCAR
   `undef T_XSR
   `undef T_RC
   `undef T_XP
   `undef NUM_INIT_REF
   `undef T_WTR
   `undef S_READY_VALID
   `undef S_DOUT_VALID_LOW
   `undef SF_ROW_ADDR_WIDTH
   `undef SF_COL_ADDR_WIDTH
   `undef SF_BANK_ADDR_WIDTH
   `undef SF_CAS_LATENCY
   `undef SF_T_RCD
   `undef SF_T_RC
   `undef T_RC_SET0
   `undef T_AS_SET0
   `undef T_WR_SET0
   `undef T_WP_SET0
   `undef T_BTA_SET0
   `undef T_PRC_SET0
   `undef PAGE_MODE_SET0
   `undef PAGE_SIZE_SET0
   `undef READY_MODE_SET0
   `undef LOW_FREQ_DEV_SET0
   `undef SM_READ_PIPE_SET0
   `undef SM_DATA_WIDTH_SET0
   `undef T_RC_SET1
   `undef T_AS_SET1
   `undef T_WR_SET1
   `undef T_WP_SET1
   `undef T_BTA_SET1
   `undef T_PRC_SET1
   `undef PAGE_MODE_SET1
   `undef PAGE_SIZE_SET1
   `undef READY_MODE_SET1
   `undef LOW_FREQ_DEV_SET1
   `undef SM_READ_PIPE_SET1
   `undef SM_DATA_WIDTH_SET1
   `undef T_RC_SET2
   `undef T_AS_SET2
   `undef T_WR_SET2
   `undef T_WP_SET2
   `undef T_BTA_SET2
   `undef T_PRC_SET2
   `undef PAGE_MODE_SET2
   `undef PAGE_SIZE_SET2
   `undef READY_MODE_SET2
   `undef LOW_FREQ_DEV_SET2
   `undef SM_READ_PIPE_SET2
   `undef SM_DATA_WIDTH_SET2
   `undef MODEL_SIZE_CS0
   `undef MODEL_DWIDTH_CS0
   `undef MODEL_SIZE_CS1
   `undef MODEL_DWIDTH_CS1
   `undef MODEL_SIZE_CS2
   `undef MODEL_DWIDTH_CS2
   `undef MODEL_SIZE_CS3
   `undef MODEL_DWIDTH_CS3
   `undef MODEL_SIZE_CS4
   `undef MODEL_DWIDTH_CS4
   `undef MODEL_SIZE_CS5
   `undef MODEL_DWIDTH_CS5
   `undef MODEL_SIZE_CS6
   `undef MODEL_DWIDTH_CS6
   `undef MODEL_SIZE_CS7
   `undef MODEL_DWIDTH_CS7
   `undef BLOCK_SIZE0
   `undef BLOCK_SIZE1
   `undef BLOCK_SIZE2
   `undef BLOCK_SIZE3
   `undef BLOCK_SIZE4
   `undef BLOCK_SIZE5
   `undef BLOCK_SIZE6
   `undef BLOCK_SIZE7
   `undef M_DATA_WIDTH
   `undef M_ADDR_WIDTH
   `undef HADDR_SIZE32
   `undef S_RD_DATA_WIDTH
   `undef USE_SIDEBAND_SAMPLE
   `undef INCLUDE_INTERNAL_TESTS
   `undef ENCODED_S_COL_ADDR_WIDTH_1
   `undef ENCODED_S_ROW_ADDR_WIDTH_1
   `undef ENCODED_S_BANK_ADDR_WIDTH_1
   `undef ENCODED_S_DATA_WIDTH
   `undef ENCODED_T_RC_1
   `undef ENCODED_EXT_T_XSR_1
   `undef ENCODED_LOW_T_XSR_1
   `undef ENCODED_T_XSR_1
   `undef ENCODED_T_RCAR_1
   `undef ENCODED_T_WR_1
   `undef ENCODED_T_RP_1
   `undef ENCODED_T_RCD_1
   `undef ENCODED_T_RAS_MIN_1
   `undef ENCODED_EXT_CAS_LATENCY_1
   `undef ENCODED_LOW_CAS_LATENCY_1
   `undef ENCODED_CAS_LATENCY_1
   `undef ENCODED_T_WTR_1
   `undef ENCODED_NUM_INIT_REF_1
   `undef ENCODED_T_INIT
   `undef ENCODED_S_READY_VALID
   `undef ENCODED_OPEN_BANKS_1
   `undef ENCODED_READ_PIPE
   `undef ENCODED_T_REF
   `undef ENCODED_REG_SELECT0
   `undef ENCODED_CHIP_SELECT0_MEM
   `undef ENCODED_BLOCK_SIZE0
   `undef ENCODED_REG_SELECT1
   `undef ENCODED_CHIP_SELECT1_MEM
   `undef ENCODED_BLOCK_SIZE1
   `undef ENCODED_REG_SELECT2
   `undef ENCODED_CHIP_SELECT2_MEM
   `undef ENCODED_BLOCK_SIZE2
   `undef ENCODED_REG_SELECT3
   `undef ENCODED_CHIP_SELECT3_MEM
   `undef ENCODED_BLOCK_SIZE3
   `undef ENCODED_REG_SELECT4
   `undef ENCODED_CHIP_SELECT4_MEM
   `undef ENCODED_BLOCK_SIZE4
   `undef ENCODED_REG_SELECT5
   `undef ENCODED_CHIP_SELECT5_MEM
   `undef ENCODED_BLOCK_SIZE5
   `undef ENCODED_REG_SELECT6
   `undef ENCODED_CHIP_SELECT6_MEM
   `undef ENCODED_BLOCK_SIZE6
   `undef ENCODED_REG_SELECT7
   `undef ENCODED_CHIP_SELECT7_MEM
   `undef ENCODED_BLOCK_SIZE7
   `undef ENCODED_SM_READ_PIPE_SET0
   `undef ENCODED_LOW_FREQ_DEV_SET0
   `undef ENCODED_READY_MODE_SET0
   `undef ENCODED_PAGE_SIZE_SET0
   `undef ENCODED_PAGE_MODE_SET0
   `undef ENCODED_T_PRC_SET0_1
   `undef ENCODED_T_BTA_SET0
   `undef ENCODED_T_WP_SET0_1
   `undef ENCODED_T_WR_SET0
   `undef ENCODED_T_AS_SET0
   `undef ENCODED_T_RC_SET0_1
   `undef ENCODED_SM_READ_PIPE_SET1
   `undef ENCODED_LOW_FREQ_DEV_SET1
   `undef ENCODED_READY_MODE_SET1
   `undef ENCODED_PAGE_SIZE_SET1
   `undef ENCODED_PAGE_MODE_SET1
   `undef ENCODED_T_PRC_SET1_1
   `undef ENCODED_T_BTA_SET1
   `undef ENCODED_T_WP_SET1_1
   `undef ENCODED_T_WR_SET1
   `undef ENCODED_T_AS_SET1
   `undef ENCODED_T_RC_SET1_1
   `undef ENCODED_SM_READ_PIPE_SET2
   `undef ENCODED_LOW_FREQ_DEV_SET2
   `undef ENCODED_READY_MODE_SET2
   `undef ENCODED_PAGE_SIZE_SET2
   `undef ENCODED_PAGE_MODE_SET2
   `undef ENCODED_T_PRC_SET2_1
   `undef ENCODED_T_BTA_SET2
   `undef ENCODED_T_WP_SET2_1
   `undef ENCODED_T_WR_SET2
   `undef ENCODED_T_AS_SET2
   `undef ENCODED_T_RC_SET2_1
   `undef ENCODED_T_RPD
   `undef ENCODED_SM_DATA_WIDTH_SET2
   `undef ENCODED_SM_DATA_WIDTH_SET1
   `undef ENCODED_SM_DATA_WIDTH_SET0
   `undef SCONR_IN
   `undef STMG0R_IN
   `undef STMG1R_IN
   `undef SCTLR_IN
   `undef SREFR_IN
   `undef SMSKR0_IN
   `undef SMSKR1_IN
   `undef SMSKR2_IN
   `undef SMSKR3_IN
   `undef SMSKR4_IN
   `undef SMSKR5_IN
   `undef SMSKR6_IN
   `undef SMSKR7_IN
   `undef SMTMGR_SET0_IN
   `undef SMTMGR_SET1_IN
   `undef SMTMGR_SET2_IN
   `undef SMCTLR_IN
   `undef MEMCTL_COMP_VERSION
   `undef MEMCTL_COMP_TYPE
   `undef VER__1_2A_COMPATIABLE_MODE_RST
   `undef DYNAMIC__RAM_TYPE_RST
   `undef USE__MOBILE_DDR_RST
   `undef ENABLE__STATIC_RST
   `undef HARD__WIRE_SDRAM_PARAMETERS_RST
   `undef HARD__WIRE_SYNCFLASH_PARAMETERS_RST
   `undef HARD__WIRE_STATIC_PARAMETERS_RST
   `undef HARD__WIRE_CIPSELECT_PARAMETRS_RST
   `undef CHIP__SEL0_REMAP_ENABLE_RST
   `undef CHIP__SEL0_ALIAS_ENABLE_RST
   `undef CHIP__SEL1_REMAP_ENABLE_RST
   `undef CHIP__SEL1_ALIAS_ENABLE_RST
   `undef N__CS_RST
   `undef H__ADDR_WIDTH_RST
   `undef H__DATA_WIDTH_RST
   `undef MAX__SM_DATA_WIDTH_RST
   `undef MAX__SM_ADDR_WIDTH_RST
   `undef MAX__S_DATA_WIDTH_RST
   `undef MAX__S_BANK_ADDR_WIDTH_RST
   `undef MAX__S_ADDR_WIDTH_RST
   `undef COMP_PARAMS_1_RST
   `undef COMP_PARAMS_2_RST
   `undef RM_BCM01
   `undef RM_BCM02
   `undef RM_BCM03
   `undef RM_BCM05
   `undef RM_BCM06
   `undef RM_BCM07
   `undef RM_BCM08
   `undef RM_BCM09
   `undef RM_BCM10
   `undef RM_BCM11
   `undef RM_BCM12
   `undef RM_BCM15
   `undef RM_BCM16
   `undef RM_BCM21
   `undef RM_BCM22
   `undef RM_BCM23
   `undef RM_BCM24
   `undef RM_BCM25
   `undef RM_BCM26
   `undef RM_BCM27
   `undef RM_BCM28
   `undef RM_BCM29
   `undef RM_BCM30
   `undef RM_BCM31
   `undef RM_BCM32
   `undef RM_BCM43
   `undef RM_BCM44
   `undef RM_BCM46_A
   `undef RM_BCM46_B
   `undef RM_BCM46_C
   `undef RM_BCM46_D
   `undef RM_BCM47
   `undef RM_BCM51
   `undef RM_BCM52
   `undef RM_BCM53
   `undef RM_BCM54
   `undef RM_BCM55
   `undef RM_BCM57
   `undef RM_BCM58
   `undef RM_BCM59
   `undef RM_BCM64
   `undef RM_BCM65
   `undef RM_BCM66
   `undef RM_BCM71
   `undef RM_BCM72
   `undef RM_BCM73
   `undef RM_BCM76
   `undef CONFIG_REG_ADDR
   `undef SDRAM_TIMING_REG0_ADDR
   `undef SDRAM_TIMING_REG1_ADDR
   `undef CONTROL_REG_ADDR
   `undef REFRESH_REG_ADDR
   `undef CHIPSEL_REG0_LOW_ADDR
   `undef CHIPSEL_REG1_LOW_ADDR
   `undef CHIPSEL_REG2_LOW_ADDR
   `undef CHIPSEL_REG3_LOW_ADDR
   `undef CHIPSEL_REG4_LOW_ADDR
   `undef CHIPSEL_REG5_LOW_ADDR
   `undef CHIPSEL_REG6_LOW_ADDR
   `undef CHIPSEL_REG7_LOW_ADDR
   `undef CHIPSEL_REG0_HIGH_ADDR
   `undef CHIPSEL_REG1_HIGH_ADDR
   `undef CHIPSEL_REG2_HIGH_ADDR
   `undef CHIPSEL_REG3_HIGH_ADDR
   `undef CHIPSEL_REG4_HIGH_ADDR
   `undef CHIPSEL_REG5_HIGH_ADDR
   `undef CHIPSEL_REG6_HIGH_ADDR
   `undef CHIPSEL_REG7_HIGH_ADDR
   `undef MASK_REG_ADDR1
   `undef MASK_REG_ADDR2
   `undef MASK_REG_ADDR3
   `undef MASK_REG_ADDR4
   `undef MASK_REG_ADDR5
   `undef MASK_REG_ADDR6
   `undef MASK_REG_ADDR7
   `undef MASK_REG_ADDR8
   `undef CHIPSEL0_LOW_ALIAS_REG_ADDR
   `undef CHIPSEL1_LOW_ALIAS_REG_ADDR
   `undef CHIPSEL0_HIGH_ALIAS_REG_ADDR
   `undef CHIPSEL1_HIGH_ALIAS_REG_ADDR
   `undef CHIPSEL0_LOW_REMAP_REG_ADDR
   `undef CHIPSEL1_LOW_REMAP_REG_ADDR
   `undef CHIPSEL0_HIGH_REMAP_REG_ADDR
   `undef CHIPSEL1_HIGH_REMAP_REG_ADDR
   `undef SMTMGR_SET0_REG_ADDR
   `undef SMTMGR_SET1_REG_ADDR
   `undef SMTMGR_SET2_REG_ADDR
   `undef FLASH_TRPDR_REG_ADDR
   `undef SMCTLR_REG_ADDR
   `undef SYFLASH_OPCODE_REG_ADDR
   `undef EXN_MODE_REG_ADDR
   `undef SFCONR_REG_ADDR
   `undef SFCTLR_REG_ADDR
   `undef SYNCFLASH_TIMING_REG_ADDR
   `undef MEMCTL_COMP_TYPE_ADDR
   `undef MEMCTL_COMP_VERSION_ADDR
   `undef MEMCTL_COMP_PARAMS_1_ADDR
   `undef MEMCTL_COMP_PARAMS_2_ADDR
   `undef CR_IDLE
   `undef CR_16RD1
   `undef CR_16RD2
   `undef CR_16WR1
   `undef CR_16WR2
   `undef CR_WR_DONE
   `undef CR_DONE
   `undef SMCR_IDLE
   `undef SMCR_16RD1
   `undef SMCR_16RD2
   `undef SMCR_16WR1
   `undef SMCR_16WR2
   `undef SMCR_WR_DONE
   `undef SMCR_DONE
   `undef AFIFO_IN_WIDTH
   `undef AFIFO_OUT_WIDTH
   `undef DFIFO_IN_WIDTH
   `undef DFIFO_OUT_WIDTH
   `undef TWO_TO_ONE
   `undef IN_START_DSDC
   `undef IN_WAIT_DSDC
   `undef IN_CKE_DSDC
   `undef IN_PREC1_DSDC
   `undef IN_LD_EMR_DSDC
   `undef IN_LD_MR1_DSDC
   `undef IN_PREC2_DSDC
   `undef IN_REF_DSDC
   `undef IN_LD_MR2_DSDC
   `undef SR_EN_RF_DSDC
   `undef SELF_REF_DSDC
   `undef SR_EXIT_DSDC
   `undef SR_EX_RF_DSDC
   `undef POWER_DOWN_DSDC
   `undef PD_EXIT_WAIT_DSDC
   `undef PD_RF_EXIT_DSDC
   `undef PD_REF_DSDC
   `undef LOAD_MR_DSDC
   `undef LOAD_EMR_DSDC
   `undef OP_IDLE_DSDC
   `undef OP_WAIT_DSDC
   `undef DEEP_POWER_DOWN_DSDC
   `undef WAIT_DSDC
   `undef IDLE_DSDC
   `undef ACT_DSDC
   `undef READ_DSDC
   `undef R_DATA_DSDC
   `undef R_TERM_DSDC
   `undef R_RAS_DSDC
   `undef R_PREC_DSDC
   `undef WRITE_DSDC
   `undef W_POP_DSDC
   `undef W_WR_RAS_DSDC
   `undef W_PREC_DSDC
   `undef W_RF_WR_DSDC
   `undef INT_RF_PREC_DSDC
   `undef INT_REF_DSDC
   `undef PREC_DSDC
   `undef AUTO_REF_DSDC
   `undef RW_IDLE_DSDC
   `undef T_MRD_DSDC
   `undef BYT_CNT
   `undef WRD_CNT
   `undef DM_IDLE
   `undef DM_READ
   `undef DM_WRITE
   `undef DM_WAIT
   `undef DM_TERM
   `undef SD_GNT
   `undef SF_GNT
`define cb_dummy_parameter_definition 1
`undef  cb_dummy_parameter_definition
