# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    set ::env(RT_TMP) "./.Xil/Vivado-23142-fyh-OptiPlex-3020/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a100tfgg484-2

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/clocking/mig_7series_v2_3_tempmon.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/clocking/mig_7series_v2_3_iodelay_ctrl.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/clocking/mig_7series_v2_3_clk_ibuf.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/clocking/mig_7series_v2_3_infrastructure.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/phy/mig_7series_v2_3_poc_pd.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/phy/mig_7series_v2_3_ddr_if_post_fifo.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/phy/mig_7series_v2_3_ddr_of_pre_fifo.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_wrlvl_off_delay.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_dqs_found_cal_hr.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_top.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/phy/mig_7series_v2_3_poc_edge_store.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/phy/mig_7series_v2_3_poc_meta.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_ocd_lim.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_ocd_cntlr.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_oclkdelay_cal.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_ocd_po_cntlr.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_wrcal.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/phy/mig_7series_v2_3_ddr_byte_group_io.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/phy/mig_7series_v2_3_ddr_mc_phy.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/phy/mig_7series_v2_3_ddr_prbs_gen.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_ocd_edge.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/phy/mig_7series_v2_3_poc_tap_base.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/phy/mig_7series_v2_3_ddr_calib_top.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_ocd_mux.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/phy/mig_7series_v2_3_ddr_byte_lane.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_rdlvl.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/phy/mig_7series_v2_3_ddr_mc_phy_wrapper.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_4lanes.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/phy/mig_7series_v2_3_poc_cc.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_prbs_rdlvl.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_tempmon.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/phy/mig_7series_v2_3_poc_top.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_init.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_wrlvl.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_ck_addr_cmd_delay.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_dqs_found_cal.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_ocd_samp.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_ocd_data.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/controller/mig_7series_v2_3_bank_mach.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/controller/mig_7series_v2_3_arb_mux.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/controller/mig_7series_v2_3_rank_cntrl.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/controller/mig_7series_v2_3_bank_queue.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/controller/mig_7series_v2_3_mc.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/controller/mig_7series_v2_3_col_mach.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/controller/mig_7series_v2_3_bank_common.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/controller/mig_7series_v2_3_round_robin_arb.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/controller/mig_7series_v2_3_bank_compare.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/controller/mig_7series_v2_3_arb_select.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/controller/mig_7series_v2_3_bank_state.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/controller/mig_7series_v2_3_arb_row_col.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/controller/mig_7series_v2_3_rank_mach.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/controller/mig_7series_v2_3_rank_common.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/controller/mig_7series_v2_3_bank_cntrl.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/ip_top/mig_7series_v2_3_mem_intfc.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/ip_top/mig_7series_v2_3_memc_ui_top_axi.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/axi/mig_7series_v2_3_ddr_r_upsizer.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/axi/mig_7series_v2_3_ddr_command_fifo.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/axi/mig_7series_v2_3_ddr_comparator_sel.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/axi/mig_7series_v2_3_axi_ctrl_addr_decode.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/axi/mig_7series_v2_3_axi_mc_cmd_fsm.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/axi/mig_7series_v2_3_axi_ctrl_reg.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/axi/mig_7series_v2_3_axi_mc_b_channel.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/axi/mig_7series_v2_3_axi_mc_wr_cmd_fsm.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/axi/mig_7series_v2_3_axi_mc_wrap_cmd.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/axi/mig_7series_v2_3_axi_mc_ar_channel.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/axi/mig_7series_v2_3_ddr_w_upsizer.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/axi/mig_7series_v2_3_axi_mc_simple_fifo.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/axi/mig_7series_v2_3_ddr_carry_and.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/axi/mig_7series_v2_3_ddr_axi_register_slice.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/axi/mig_7series_v2_3_axi_mc_r_channel.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/axi/mig_7series_v2_3_axi_mc_fifo.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/axi/mig_7series_v2_3_axi_mc_aw_channel.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/axi/mig_7series_v2_3_ddr_comparator_sel_static.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/axi/mig_7series_v2_3_ddr_axic_register_slice.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/axi/mig_7series_v2_3_axi_mc_incr_cmd.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/axi/mig_7series_v2_3_ddr_carry_latch_and.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/axi/mig_7series_v2_3_axi_mc_cmd_translator.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/axi/mig_7series_v2_3_axi_ctrl_top.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/axi/mig_7series_v2_3_axi_mc.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/axi/mig_7series_v2_3_ddr_axi_upsizer.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/axi/mig_7series_v2_3_ddr_comparator.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/axi/mig_7series_v2_3_axi_mc_cmd_arbiter.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/axi/mig_7series_v2_3_axi_ctrl_reg_bank.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/axi/mig_7series_v2_3_axi_ctrl_read.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/axi/mig_7series_v2_3_ddr_carry_or.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/axi/mig_7series_v2_3_ddr_a_upsizer.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/axi/mig_7series_v2_3_axi_mc_w_channel.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/axi/mig_7series_v2_3_axi_ctrl_write.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/axi/mig_7series_v2_3_ddr_carry_latch_or.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/ecc/mig_7series_v2_3_ecc_merge_enc.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/ecc/mig_7series_v2_3_ecc_dec_fix.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/ecc/mig_7series_v2_3_ecc_gen.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/ecc/mig_7series_v2_3_ecc_buf.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/ecc/mig_7series_v2_3_fi_xor.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/ui/mig_7series_v2_3_ui_wr_data.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/ui/mig_7series_v2_3_ui_rd_data.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/ui/mig_7series_v2_3_ui_top.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/ui/mig_7series_v2_3_ui_cmd.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/xilinx_ddr3_if.v
      /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.srcs/sources_1/ip/xilinx_ddr3_if/xilinx_ddr3_if/user_design/rtl/xilinx_ddr3_if_mig.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-23142-fyh-OptiPlex-3020/realtime/xilinx_ddr3_if_synth.xdc
    rt::sdcChecksum
    set rt::top xilinx_ddr3_if
    set rt::ioInsertion false
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
    rt::set_parameter webTalkPath {/home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_ddr3_if/xilinx_ddr3_if.cache/wt}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-23142-fyh-OptiPlex-3020/"
    if {$rt::useElabCache == false} {
      rt::run_synthesis -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
    }


    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
