set VSIM_IP_LIBS " \
  -L apb_gpio_lib \
  -L axi_slice_dc_lib \
  -L apb_event_unit_lib \
  -L axi_node_lib \
  -L riscv_lib \
  -L apb_pulpino_lib \
  -L axi_mem_if_DP_lib \
  -L axi_slice_lib \
  -L apb_uart_lib \
  -L apb_spi_master_lib \
  -L apb_timer_lib \
  -L apb_pwm_lib \
  -L axi2apb_lib \
  -L axi_spi_slave_lib \
  -L apb_i2c_lib \
  -L adv_dbg_if_lib \
  -L core2axi_lib \
  -L apb_node_lib \
  -L apb2per_lib \
  -L ahb_ann_lib \
  -L ahb_camera_lib \
  -L ahb_common_lib \
  -L ahb_emmc_lib \
  -L ahb_memctl_lib \
  -L ahb_node_lib \
  -L ahb_x2h_lib \
"
