# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a100tfgg484-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/hetingting/artix7-board_use_mig/artix7/ips/xilinx_ahblite_axi_bridge/h2x_bridge.cache/wt [current_project]
set_property parent.project_path /home/hetingting/artix7-board_use_mig/artix7/ips/xilinx_ahblite_axi_bridge/h2x_bridge.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_ip /home/hetingting/artix7-board_use_mig/artix7/ips/xilinx_ahblite_axi_bridge/h2x_bridge.srcs/sources_1/ip/h2x_bridge/h2x_bridge.xci
set_property is_locked true [get_files /home/hetingting/artix7-board_use_mig/artix7/ips/xilinx_ahblite_axi_bridge/h2x_bridge.srcs/sources_1/ip/h2x_bridge/h2x_bridge.xci]

synth_design -top h2x_bridge -part xc7a100tfgg484-2 -mode out_of_context
rename_ref -prefix_all h2x_bridge_
write_checkpoint -noxdef h2x_bridge.dcp
catch { report_utilization -file h2x_bridge_utilization_synth.rpt -pb h2x_bridge_utilization_synth.pb }
if { [catch {
  file copy -force /home/hetingting/artix7-board_use_mig/artix7/ips/xilinx_ahblite_axi_bridge/h2x_bridge.runs/h2x_bridge_synth_1/h2x_bridge.dcp /home/hetingting/artix7-board_use_mig/artix7/ips/xilinx_ahblite_axi_bridge/h2x_bridge.srcs/sources_1/ip/h2x_bridge/h2x_bridge.dcp
} _RESULT ] } { 
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub /home/hetingting/artix7-board_use_mig/artix7/ips/xilinx_ahblite_axi_bridge/h2x_bridge.srcs/sources_1/ip/h2x_bridge/h2x_bridge_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub /home/hetingting/artix7-board_use_mig/artix7/ips/xilinx_ahblite_axi_bridge/h2x_bridge.srcs/sources_1/ip/h2x_bridge/h2x_bridge_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim /home/hetingting/artix7-board_use_mig/artix7/ips/xilinx_ahblite_axi_bridge/h2x_bridge.srcs/sources_1/ip/h2x_bridge/h2x_bridge_funcsim.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim /home/hetingting/artix7-board_use_mig/artix7/ips/xilinx_ahblite_axi_bridge/h2x_bridge.srcs/sources_1/ip/h2x_bridge/h2x_bridge_funcsim.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
