# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_clock_div2/xilinx_clock_div2.srcs/sources_1/ip/xilinx_clock_div2/xilinx_clock_div2.xci
# IP: The module: 'xilinx_clock_div2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_clock_div2/xilinx_clock_div2.srcs/sources_1/ip/xilinx_clock_div2/xilinx_clock_div2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_clock_div2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_clock_div2/xilinx_clock_div2.srcs/sources_1/ip/xilinx_clock_div2/xilinx_clock_div2.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_clock_div2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_clock_div2/xilinx_clock_div2.srcs/sources_1/ip/xilinx_clock_div2/xilinx_clock_div2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_clock_div2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_clock_div2/xilinx_clock_div2.srcs/sources_1/ip/xilinx_clock_div2/xilinx_clock_div2.xci
# IP: The module: 'xilinx_clock_div2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_clock_div2/xilinx_clock_div2.srcs/sources_1/ip/xilinx_clock_div2/xilinx_clock_div2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_clock_div2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_clock_div2/xilinx_clock_div2.srcs/sources_1/ip/xilinx_clock_div2/xilinx_clock_div2.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_clock_div2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/fyh/emmc_test/artix7-board/artix7/ips/xilinx_clock_div2/xilinx_clock_div2.srcs/sources_1/ip/xilinx_clock_div2/xilinx_clock_div2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_clock_div2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
