##################################################################################################
##
##  Xilinx, Inc. 2010            www.xilinx.com
##  ?? 7? 5 09:16:37 2017
##  Generated by MIG Version 2.3
##
##################################################################################################
##  File name :       xilinx_ddr3_if.xdc
##  Details :     Constraints file
##                    FPGA Family:       ARTIX7
##                    FPGA Part:         XC7A100T-FGG484
##                    Speedgrade:        -2
##                    Design Entry:      VERILOG
##                    Frequency:         0 MHz
##                    Time Period:       2500 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->Components->MT41K256M16XX-125
## Data Width: 32
## Time Period: 2500
## Data Mask: 1
##################################################################################################

create_clock -period 5.000 [get_ports clk_p]

############## NET - IOSTANDARD ##################


# PadFunction: IO_L2P_T0_AD12P_35

# PadFunction: IO_L5P_T0_AD13P_35

# PadFunction: IO_L1N_T0_AD4N_35

# PadFunction: IO_L6P_T0_35

# PadFunction: IO_L2N_T0_AD12N_35

# PadFunction: IO_L5N_T0_AD13N_35

# PadFunction: IO_L1P_T0_AD4P_35

# PadFunction: IO_L4P_T0_35

# PadFunction: IO_L11P_T1_SRCC_35

# PadFunction: IO_L11N_T1_SRCC_35

# PadFunction: IO_L8P_T1_AD14P_35

# PadFunction: IO_L10N_T1_AD15N_35

# PadFunction: IO_L7N_T1_AD6N_35

# PadFunction: IO_L10P_T1_AD15P_35

# PadFunction: IO_L7P_T1_AD6P_35

# PadFunction: IO_L12P_T1_MRCC_35

# PadFunction: IO_L18N_T2_35

# PadFunction: IO_L16P_T2_35

# PadFunction: IO_L14P_T2_SRCC_35

# PadFunction: IO_L17N_T2_35

# PadFunction: IO_L14N_T2_SRCC_35

# PadFunction: IO_L17P_T2_35

# PadFunction: IO_L13N_T2_MRCC_35

# PadFunction: IO_L18P_T2_35

# PadFunction: IO_L20N_T3_35

# PadFunction: IO_L19P_T3_35

# PadFunction: IO_L20P_T3_35

# PadFunction: IO_L22N_T3_35

# PadFunction: IO_L23P_T3_35

# PadFunction: IO_L24N_T3_35

# PadFunction: IO_L24P_T3_35

# PadFunction: IO_L22P_T3_35

# PadFunction: IO_L6N_T0_VREF_34

# PadFunction: IO_L1N_T0_34

# PadFunction: IO_L4N_T0_34

# PadFunction: IO_L4P_T0_34

# PadFunction: IO_L5N_T0_34

# PadFunction: IO_L2P_T0_34

# PadFunction: IO_L2N_T0_34

# PadFunction: IO_L1P_T0_34

# PadFunction: IO_L5P_T0_34

# PadFunction: IO_L6P_T0_34

# PadFunction: IO_L7N_T1_34

# PadFunction: IO_L10N_T1_34

# PadFunction: IO_L10P_T1_34

# PadFunction: IO_L8N_T1_34

# PadFunction: IO_L11N_T1_SRCC_34

# PadFunction: IO_L11P_T1_SRCC_34

# PadFunction: IO_L9P_T1_DQS_34

# PadFunction: IO_L9N_T1_DQS_34

# PadFunction: IO_L12P_T1_MRCC_34

# PadFunction: IO_L12N_T1_MRCC_34

# PadFunction: IO_L7P_T1_34

# PadFunction: IO_L15P_T2_DQS_34

# PadFunction: IO_L14P_T2_SRCC_34

# PadFunction: IO_L14N_T2_SRCC_34

# PadFunction: IO_L8P_T1_34

# PadFunction: IO_L4N_T0_35

# PadFunction: IO_L8N_T1_AD14N_35

# PadFunction: IO_L16N_T2_35

# PadFunction: IO_L23N_T3_35

# PadFunction: IO_L13P_T2_MRCC_34
set_property IOSTANDARD DIFF_SSTL15 [get_ports clk_p]

# PadFunction: IO_L13N_T2_MRCC_34
set_property IOSTANDARD DIFF_SSTL15 [get_ports clk_n]
set_property PACKAGE_PIN R4 [get_ports clk_p]
set_property PACKAGE_PIN T4 [get_ports clk_n]

# PadFunction: IO_L3P_T0_DQS_AD5P_35

# PadFunction: IO_L3N_T0_DQS_AD5N_35

# PadFunction: IO_L9P_T1_DQS_AD7P_35

# PadFunction: IO_L9N_T1_DQS_AD7N_35

# PadFunction: IO_L15P_T2_DQS_35

# PadFunction: IO_L15N_T2_DQS_35

# PadFunction: IO_L21P_T3_DQS_35

# PadFunction: IO_L21N_T3_DQS_35

# PadFunction: IO_L3P_T0_DQS_34

# PadFunction: IO_L3N_T0_DQS_34




## set_property LOC PHASER_IN_PHY_X1Y7 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
## set_property LOC PHASER_IN_PHY_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
## set_property LOC PHASER_IN_PHY_X1Y5 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]










current_instance top_i/ppu_top_i/ddr3_if_inst/xilinx_ddr3_if_inst
set_multicycle_path -setup -from [get_cells -hier -filter {NAME =~ */mc0/mc_read_idle_r_reg}] -to [get_cells -hier -filter {NAME =~ */input_[?].iserdes_dq_.iserdesdq}] 6

set_multicycle_path -hold -from [get_cells -hier -filter {NAME =~ */mc0/mc_read_idle_r_reg}] -to [get_cells -hier -filter {NAME =~ */input_[?].iserdes_dq_.iserdesdq}] 5



set_false_path -through [get_pins -filter {NAME =~ */DQSFOUND} -of [get_cells -hier -filter {REF_NAME == PHASER_IN_PHY}]]

set_multicycle_path -setup -start -through [get_pins -filter {NAME =~ */OSERDESRST} -of [get_cells -hier -filter {REF_NAME == PHASER_OUT_PHY}]] 2
set_multicycle_path -hold -start -through [get_pins -filter {NAME =~ */OSERDESRST} -of [get_cells -hier -filter {REF_NAME == PHASER_OUT_PHY}]] 1

set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/* && IS_SEQUENTIAL}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/device_temp_sync_r1*}] 5.000
set_max_delay -datapath_only -from [get_cells -hier *rstdiv0_sync_r1_reg*] -to [get_pins -filter {NAME =~ */RESET} -of [get_cells -hier -filter {REF_NAME == PHY_CONTROL}]] 5.000

set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *ddr3_infrastructure/rstdiv0_sync_r1_reg*}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/xadc_supplied_temperature.rst_r1*}] 10.000



