# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/hetingting/artix7-board_use_mig/artix7/ips/xilinx_clock_2x/xilinx_clock_2x.srcs/sources_1/ip/xilinx_clock_2x/xilinx_clock_2x.xci
# IP: The module: 'xilinx_clock_2x' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hetingting/artix7-board_use_mig/artix7/ips/xilinx_clock_2x/xilinx_clock_2x.srcs/sources_1/ip/xilinx_clock_2x/xilinx_clock_2x_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_clock_2x'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/hetingting/artix7-board_use_mig/artix7/ips/xilinx_clock_2x/xilinx_clock_2x.srcs/sources_1/ip/xilinx_clock_2x/xilinx_clock_2x.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_clock_2x'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/hetingting/artix7-board_use_mig/artix7/ips/xilinx_clock_2x/xilinx_clock_2x.srcs/sources_1/ip/xilinx_clock_2x/xilinx_clock_2x_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_clock_2x'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/hetingting/artix7-board_use_mig/artix7/ips/xilinx_clock_2x/xilinx_clock_2x.srcs/sources_1/ip/xilinx_clock_2x/xilinx_clock_2x.xci
# IP: The module: 'xilinx_clock_2x' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hetingting/artix7-board_use_mig/artix7/ips/xilinx_clock_2x/xilinx_clock_2x.srcs/sources_1/ip/xilinx_clock_2x/xilinx_clock_2x_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_clock_2x'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/hetingting/artix7-board_use_mig/artix7/ips/xilinx_clock_2x/xilinx_clock_2x.srcs/sources_1/ip/xilinx_clock_2x/xilinx_clock_2x.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_clock_2x'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/hetingting/artix7-board_use_mig/artix7/ips/xilinx_clock_2x/xilinx_clock_2x.srcs/sources_1/ip/xilinx_clock_2x/xilinx_clock_2x_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_clock_2x'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
